version: '2'
services:
  ipfs:
    image: ipfs/go-ipfs:latest
    ports:
      - 8080:8080
      - 4001:4001
      - 5001:5001
    volumes:
      - /data/ipfs:/data/ipfs
  ipfs-cluster:
    image: ipfs/ipfs-cluster:v0.4.0
    ports:
      - 9096:9096
      - 9094:9094
    volumes:
      - /data/ipfs-cluster:/data/ipfs-cluster