version: '3'
#docker exec ee5a36ab61a0 ipfs bootstrap rm --all
services:
  ipfs:
    build:
      context: .
      dockerfile: ipfs/dockerfile
    ports:
      - 8080:8080
      - 4002:4002
      - 4001:4001
      - 5001:5001
    volumes:
      - /data/ipfs:/data/ipfs

  cluster:
    build:
      context: .
      dockerfile: cluster/dockerfile
    depends_on:
      - ipfs
    ports:
      - 9096:9096
      - 9095:9095
      - 9094:9094
    volumes:
      - /data/ipfs-cluster:/data/ipfs-cluster
